name: Substrate Build
on:
  push:
    branches:
      - gitref
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          # sudo apt-get install at-spi2-core build-essential libgtk-3-dev libxtst-dev libavcodec-dev libavformat-dev libasound2-dev
          # sudo apt-get install xvfb tigervnc-standalone-server tigervnc-common
          echo "github ref"
          echo ${{github.ref}}
          echo "Push ref"
          echo ${{github.event.push.ref}}
          echo "Event"
          echo ${{github.event}}