name: Substrate Build
on:
  push:
    branches:
      - android
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [host, android]
    steps:
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install at-spi2-core build-essential libgtk-3-dev libxtst-dev libavcodec-dev libavformat-dev libasound2-dev libgl-dev
          sudo apt-get install xvfb tigervnc-standalone-server tigervnc-common

      - name: Install packages (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install --HEAD libusbmuxd libimobiledevice

      - name: Install GraalVM (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p $HOME/graalvm && cd $HOME/graalvm
          wget https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.2-latest.zip
          unzip graalvm-svm-linux-20.2-latest && cd $GITHUB_WORKSPACE

      - name: Install GraalVM (MacOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p $HOME/graalvm && cd $HOME/graalvm
          wget https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.2-latest.zip
          unzip graalvm-svm-darwin-20.2-latest && cd $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install JavaFX static libs
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/javafx-static.sh $TARGET
        env:
          TARGET = ${{ matrix.target }}

      - name: Install Android SDK and NDK
        if: matrix.target == 'android'
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/android.sh

      - name: Run Host Tests (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'host'
        run: |
          export GRAALVM_HOME=$HOME/graalvm/graalvm-svm-linux-20.2-latest
          export JAVAFX_STATIC_SDK=$HOME/javafx-static-libs-linux/sdk
          export DISPLAY=:90
          mkdir /home/runner/.vnc
          echo 123456 | vncpasswd -f > /home/runner/.vnc/passwd
          chmod -v 600 /home/runner/.vnc/passwd
          vncserver :90 -localhost -nolisten tcp
          sh gradlew -i test
          vncserver -kill :90

      - name: Run Host Tests (MacOS)
        if: matrix.os == 'macos-latest' && matrix.target == 'host'
        run: |
          export GRAALVM_HOME=$HOME/graalvm/graalvm-svm-darwin-20.2-latest
          export JAVAFX_STATIC_SDK=$HOME/javafx-static-libs-darwin/sdk
          export JAVAFX_STATIC_SDK_IOS=$HOME/javafx-static-libs-ios/sdk
          sh gradlew -i test
          
      - name: Run Android Tests (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'android'
        run: |
          export GRAALVM_HOME=$HOME/graalvm/graalvm-svm-linux-20.2-latest
          export JAVAFX_STATIC_SDK=$HOME/javafx-static-libs-linux/sdk
          export ANDROID_SDK=$HOME/android-sdk
          export ANDROID_NDK=$HOME/android-sdk/ndk-bundle
          sh gradlew -i test -Pandroid
  
      - name: Run Android Tests (MacOS)
        if: matrix.os == 'macos-latest' && matrix.target == 'android'
        run: |
          export GRAALVM_HOME=$HOME/graalvm/graalvm-svm-darwin-20.2-latest
          export JAVAFX_STATIC_SDK=$HOME/javafx-static-libs-darwin/sdk
          export JAVAFX_STATIC_SDK_IOS=$HOME/javafx-static-libs-ios/sdk
          export ANDROID_SDK=$HOME/android-sdk
          export ANDROID_NDK=$HOME/android-sdk/ndk-bundle
          ./gradlew -i test -Pandroid

      - name: Build project
        run: sh gradlew -i build -x test

      - name: Deploy Snapshot
        if: runner.os == 'Linux' && github.ref == 'refs/heads/master'
        run: sh gradlew publish -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}