name: Substrate Build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
#      - name: Install packages (Linux)
#        if: runner.os == 'Linux'
#        run: |
#          sudo apt-get install at-spi2-core build-essential libgtk-3-dev libxtst-dev libavcodec-dev libavformat-dev libasound2-dev
#          sudo apt-get install xvfb

#      - name: Install GraalVM (Linux)
#        if: runner.os == 'Linux'
#        run: |
#          mkdir -p $HOME/graalvm && cd $HOME/graalvm
#          wget https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.1-latest.zip
#          unzip graalvm-svm-linux-20.1-latest && cd $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Deploy to Sonatype Nexus
        run: ./gradlew publish -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}